class Heroi {
  final int indice;
  final String nome;
  final String nomeCompleto;
  final String skillVermelha;
  final String skillVerde;
  final List<String> classe;
  final String caixa;
  final String dificuldade;
  final String cartaextra;

  const Heroi({
    required this.indice,
    required this.nome,
    required this.nomeCompleto,
    required this.skillVermelha,
    required this.skillVerde,
    required this.classe,
    required this.caixa,
    required this.dificuldade,
    required this.cartaextra,
  });
}

const List<Heroi> herois = [
  Heroi(
    indice: 0,
    nome: 'Aristides',
    nomeCompleto: 'Aristides',
    skillVermelha: 'InstAgil',
    skillVerde: 'CuraGrupo',
    classe: ['Suporte'],
    caixa: 'Gelo',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 1,
    nome: 'Brad',
    nomeCompleto: 'Brad Desjajum',
    skillVermelha: 'ijDemo',
    skillVerde: 'Rebola',
    classe: ['Cura'],
    caixa: 'Padrão',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 2,
    nome: 'Broque',
    nomeCompleto: 'Broquestoque',
    skillVermelha: 'Furto',
    skillVerde: 'ijOrc',
    classe: ['Suporte'],
    caixa: 'Fogo',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 3,
    nome: 'Dedouro',
    nomeCompleto: 'Dedouro',
    skillVermelha: 'ijHumano',
    skillVerde: 'Furto',
    classe: ['Dinheiro'],
    caixa: 'Padrão',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 4,
    nome: 'Edith',
    nomeCompleto: 'Edith Grognarde',
    skillVermelha: 'Rebola',
    skillVerde: 'ijOrc',
    classe: ['Cura'],
    caixa: 'Padrão',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 5,
    nome: 'Grace',
    nomeCompleto: 'Grace Cortelimpo',
    skillVermelha: 'DanoFocado',
    skillVerde: 'ijMorto',
    classe: ['Dano'],
    caixa: 'Padrão',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 6,
    nome: 'JackSem',
    nomeCompleto: 'Jack Sembarco',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'Furto',
    classe: ['Dano', 'Dinheiro'],
    caixa: 'Gelo',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 7,
    nome: 'Lady',
    nomeCompleto: 'Lady Maria',
    skillVermelha: 'Rebola',
    skillVerde: 'InstAgil',
    classe: ['Errar', 'Dano'],
    caixa: 'Fantasma',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 8,
    nome: 'Lanky',
    nomeCompleto: 'Lanky Tirobaixo',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'DanoFocado',
    classe: ['Dano', 'Cura'],
    caixa: 'Floresta',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 9,
    nome: 'Lebron',
    nomeCompleto: 'Lebron Pele-de-Urso',
    skillVermelha: 'AutoCura',
    skillVerde: 'ijFera',
    classe: ['Dano'],
    caixa: 'Gelo',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 10,
    nome: 'Lia',
    nomeCompleto: 'Lia Mata-Demonio',
    skillVermelha: 'ijDemo',
    skillVerde: 'CuraGrupo',
    classe: ['Cura', 'Suporte'],
    caixa: 'Fogo',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 11,
    nome: 'Lianna',
    nomeCompleto: 'Lianna Grazluz',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'AutoCura',
    classe: ['Dano'],
    caixa: 'Fantasma',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 12,
    nome: 'Marga',
    nomeCompleto: 'Margarhilda',
    skillVermelha: 'AutoCura',
    skillVerde: 'Furto',
    classe: ['Dinheiro', 'Dano'],
    caixa: 'Padrão',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 13,
    nome: 'Marla',
    nomeCompleto: 'Marla Estrela-da-Manha',
    skillVermelha: 'DanoFocado',
    skillVerde: 'Rebola',
    classe: ['Cura', 'Errar'],
    caixa: 'Gelo',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 14,
    nome: 'Marvin',
    nomeCompleto: 'Marvin',
    skillVermelha: 'ijMago',
    skillVerde: 'DanoPerfu',
    classe: ['Errar', 'Dano'],
    caixa: 'Padrão',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 15,
    nome: 'Melissa',
    nomeCompleto: 'Melissa Fogareu',
    skillVermelha: 'InstAgil',
    skillVerde: 'AutoCura',
    classe: ['Dano'],
    caixa: 'Fogo',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 16,
    nome: 'Murka',
    nomeCompleto: 'Murka Cutelonublado',
    skillVermelha: 'ijFera',
    skillVerde: 'InstAgil',
    classe: ['Dano'],
    caixa: 'Padrão',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 17,
    nome: 'Randolfo',
    nomeCompleto: 'Randolfo',
    skillVermelha: 'ijMago',
    skillVerde: 'Rebola',
    classe: ['Errar', 'Suporte', 'Escudo'],
    caixa: 'Floresta',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 18,
    nome: 'Sapo',
    nomeCompleto: 'Principe Sapo',
    skillVermelha: 'Furto',
    skillVerde: 'AutoCura',
    classe: ['Dinheiro', 'Dano'],
    caixa: 'Floresta',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 19,
    nome: 'Saul',
    nomeCompleto: 'Saul Raysar',
    skillVermelha: 'ijHumano',
    skillVerde: 'Furto',
    classe: ['Cura', 'Dinheiro'],
    caixa: 'Fantasma',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 20,
    nome: 'Sirmoo',
    nomeCompleto: 'Sir Moo',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'ijMorto',
    classe: ['Cura'],
    caixa: 'Fantasma',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 21,
    nome: 'Tina',
    nomeCompleto: 'Tina Trovão',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'InstAgil',
    classe: ['Dano'],
    caixa: 'Floresta',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 22,
    nome: 'Wilrond',
    nomeCompleto: 'Wilrond',
    skillVermelha: 'InstAgil',
    skillVerde: 'CuraGrupo',
    classe: ['Dano', 'Cura'],
    caixa: 'Padrão',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 23,
    nome: 'Torm',
    nomeCompleto: 'Torm',
    skillVermelha: 'DanoFocado',
    skillVerde: 'DanoPerfu',
    classe: ['Dano'],
    caixa: 'Fogo',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 24,
    nome: 'Aang',
    nomeCompleto: 'Angnaldo Rocha',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'Voodo',
    classe: ['Suporte', 'Cura'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'Elementos',
  ),
  Heroi(
    indice: 25,
    nome: 'Alton',
    nomeCompleto: 'Alton Currie',
    skillVermelha: 'Repete',
    skillVerde: 'InstAgil',
    classe: ['Dano', 'Errar'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 26,
    nome: 'Angela',
    nomeCompleto: 'Angela A Soprano',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'InstAgil',
    classe: ['Dano', 'Cura'],
    caixa: 'W box',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 27,
    nome: 'Betty',
    nomeCompleto: 'Betty Decibel',
    skillVermelha: 'Rebola',
    skillVerde: 'Furto',
    classe: ['Dano', 'Dinheiro'],
    caixa: 'W box',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 28,
    nome: 'Contractus',
    nomeCompleto: 'Contractus Magnum',
    skillVermelha: 'NuvemCura',
    skillVerde: 'DanoPerfu',
    classe: ['Dano', 'Suporte'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 29,
    nome: 'Jack',
    nomeCompleto: 'Jack Barba Cinza',
    skillVermelha: 'Larapio',
    skillVerde: 'Furto',
    classe: ['Dano', 'Dinheiro'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 30,
    nome: 'Jorge',
    nomeCompleto: 'Jorge O Goblin',
    skillVermelha: 'Rebola',
    skillVerde: 'NuvemCura',
    classe: ['Suporte', 'Cura'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 31,
    nome: 'Lã',
    nomeCompleto: 'Lazaro Carneiro',
    skillVermelha: 'Furto',
    skillVerde: 'InstSobrev',
    classe: ['Dano', 'Dinheiro'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 32,
    nome: 'Morgana',
    nomeCompleto: 'Morgana Igneve',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'InstSobrev',
    classe: ['Cura', 'Suporte'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 33,
    nome: 'Polar',
    nomeCompleto: 'Florentina Polar',
    skillVermelha: 'DanoFocado',
    skillVerde: 'ijHumano',
    classe: ['Dano'],
    caixa: 'W box',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 34,
    nome: 'Reri',
    nomeCompleto: 'Henrique Porta',
    skillVermelha: 'Voodo',
    skillVerde: 'ijMorto',
    classe: ['Suporte', 'Dano', 'Errar'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 35,
    nome: 'Ruth',
    nomeCompleto: 'Ruth Salem',
    skillVermelha: 'Larapio',
    skillVerde: 'AutoCura',
    classe: ['Suporte', 'Dano'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 36,
    nome: 'Show',
    nomeCompleto: 'Leprenshow do milhão',
    skillVermelha: 'Furto',
    skillVerde: 'AutoCura',
    classe: ['Dinheiro', 'Dano'],
    caixa: 'W box',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 37,
    nome: 'Truta',
    nomeCompleto: 'Rei Truta',
    skillVermelha: 'ijHumano',
    skillVerde: 'InstAgil',
    classe: ['Dano'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 38,
    nome: 'Tuco',
    nomeCompleto: 'Tuco Ouropreto',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'AutoCura',
    classe: ['Dano'],
    caixa: 'W box',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 39,
    nome: 'Uni',
    nomeCompleto: 'Greg O Unico',
    skillVermelha: 'InstSobrev',
    skillVerde: 'InstAgil',
    classe: ['Dano', 'Errar'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 40,
    nome: 'Willy',
    nomeCompleto: 'Willy Capadura',
    skillVermelha: 'InstSobrev',
    skillVerde: 'Repete',
    classe: ['Suporte', 'Errar'],
    caixa: 'W box',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 41,
    nome: 'Zhang',
    nomeCompleto: 'Zhang Webb',
    skillVermelha: 'Rebola',
    skillVerde: 'NuvemCura',
    classe: ['Suporte', 'Cura'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'Mapa Estelar',
  ),
  Heroi(
    indice: 42,
    nome: 'Aurelia',
    nomeCompleto: 'Aurelia Prismalight',
    skillVermelha: 'AutoCura',
    skillVerde: 'Larapio',
    classe: ['Suporte', 'Dano', 'Versatil'],
    caixa: 'W box',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 43,
    nome: 'Barbara',
    nomeCompleto: 'Barbara',
    skillVermelha: 'Repete',
    skillVerde: 'InstSobrev',
    classe: ['Dano', 'Errar'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 44,
    nome: 'Brutus',
    nomeCompleto: 'Brutus Excelsion',
    skillVermelha: 'ijFera',
    skillVerde: 'Repete',
    classe: ['Dano', 'Versatil'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 45,
    nome: 'Cirila',
    nomeCompleto: 'Rainha Cirila Acker',
    skillVermelha: 'Repete',
    skillVerde: 'DanoFocado',
    classe: ['Dano', 'Errar'],
    caixa: 'W box',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 46,
    nome: 'Crustaceon',
    nomeCompleto: 'Crustaceon',
    skillVermelha: 'ijMago',
    skillVerde: 'NuvemCura',
    classe: ['Dano', 'Versatil'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'Casquejante',
  ),
  Heroi(
    indice: 47,
    nome: 'Dalai',
    nomeCompleto: 'Dalai Dharma',
    skillVermelha: 'Samata',
    skillVerde: 'Virya',
    classe: ['Versatil', 'Cura'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 48,
    nome: 'Death',
    nomeCompleto: 'Death Parada',
    skillVermelha: 'ijMorto',
    skillVerde: 'InstAgil',
    classe: ['Dano', 'Cura'],
    caixa: 'W box',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 49,
    nome: 'Dracon',
    nomeCompleto: 'Dracon Frozone',
    skillVermelha: 'InstSobrev',
    skillVerde: 'Larapio',
    classe: ['Dano', 'Versatil'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 50,
    nome: 'Eldor',
    nomeCompleto: 'Eldor Ansala',
    skillVermelha: 'DanoFocado',
    skillVerde: 'CuraGrupo',
    classe: ['Dano', 'Versatil'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'Aslan',
  ),
  Heroi(
    indice: 51,
    nome: 'Dungeon',
    nomeCompleto: 'The Dungeon Fighter',
    skillVermelha: 'InstSuperior',
    skillVerde: 'Vortice',
    classe: ['Dano', 'Apelão'],
    caixa: 'W box',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 52,
    nome: 'Frodo',
    nomeCompleto: 'Frodo Nogueira',
    skillVermelha: 'InstAgil',
    skillVerde: 'ijOrc',
    classe: ['Errar', 'Escudo'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 53,
    nome: 'Luffy',
    nomeCompleto: 'Monkey D. Luffy',
    skillVermelha: 'InstAgil',
    skillVerde: 'DanoPerfu',
    classe: ['Dano', 'Errar'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 54,
    nome: 'Melania',
    nomeCompleto: 'Melania D. Doom',
    skillVermelha: 'Larapio',
    skillVerde: 'Voodo',
    classe: ['Errar', 'Escudo'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 55,
    nome: 'Mognax',
    nomeCompleto: 'Mognax',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'DanoFocado',
    classe: ['Dano'],
    caixa: 'W box',
    dificuldade: 'Facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 56,
    nome: 'Poucas',
    nomeCompleto: 'Mr. Poucastrancas',
    skillVermelha: 'Fobia',
    skillVerde: 'CuraErrado',
    classe: ['Ruim'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 57,
    nome: 'Safadinha',
    nomeCompleto: 'Safa & Dinha',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'Furto',
    classe: ['Dano', 'Dinheiro'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 58,
    nome: 'Selune',
    nomeCompleto: 'Selune Luanova',
    skillVermelha: 'NuvemCura',
    skillVerde: 'Repete',
    classe: ['Cura', 'Versatil'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 59,
    nome: 'Wes',
    nomeCompleto: 'Weslorde',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'Voodo',
    classe: ['Cura', 'Versatil'],
    caixa: 'W box',
    dificuldade: 'Medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 60,
    nome: 'Will',
    nomeCompleto: 'Willquiles',
    skillVermelha: 'InstAgil',
    skillVerde: 'NuvemCura',
    classe: ['Cura', 'Versatil'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 61,
    nome: 'Xama',
    nomeCompleto: 'Irmã Xama',
    skillVermelha: 'Voodo',
    skillVerde: 'ijDemo',
    classe: ['Errar', 'Versatil'],
    caixa: 'W box',
    dificuldade: 'Dificil',
    cartaextra: 'nao',
  ),
];

class HeroiAux extends Heroi {
  const HeroiAux({
    super.skillVermelha = '',
    super.skillVerde = '',
    super.classe = const [],
    super.caixa = '',
    super.dificuldade = '',
    super.nomeCompleto = '',
    required super.indice,
    required super.nome,
    required super.cartaextra,
    
  });
}

const List<HeroiAux> heroisAux = [
  HeroiAux(indice: 0, nome: 'Elementos', cartaextra: 'Aang'),
  HeroiAux(indice: 1, nome: 'Mapa Estelar', cartaextra: 'Zhang'),
  HeroiAux(indice: 2, nome: 'Aslan', cartaextra: 'Eldor'),
  HeroiAux(indice: 3, nome: 'Casquejante', cartaextra: 'Crustaceon'),
];
