class Heroi {
  final int indice;
  final String nome;
  final String skillVermelha;
  final String skillVerde;
  final List<String> classe;
  final String caixa;
  final String dificuldade;
  final String cartaextra;

  const Heroi({
    required this.indice,
    required this.nome,
    required this.skillVermelha,
    required this.skillVerde,
    required this.classe,
    required this.caixa,
    required this.dificuldade,
    required this.cartaextra,
  });
}

const List<Heroi> herois = [
  Heroi(
    indice: 0,
    nome: 'Aristides',
    skillVermelha: 'InstAgil',
    skillVerde: 'CuraGrupo',
    classe: ['Suporte'],
    caixa: 'gelo',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 1,
    nome: 'Brad',
    skillVermelha: 'ijDemo',
    skillVerde: 'Rebola',
    classe: ['Cura'],
    caixa: 'padrão',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 2,
    nome: 'Broque',
    skillVermelha: 'Furto',
    skillVerde: 'ijOrc',
    classe: ['Suporte'],
    caixa: 'fogo',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 3,
    nome: 'Dedouro',
    skillVermelha: 'ijHumano',
    skillVerde: 'Furto',
    classe: ['Dinheiro'],
    caixa: 'padrão',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 4,
    nome: 'Edith',
    skillVermelha: 'Rebola',
    skillVerde: 'ijOrc',
    classe: ['Cura'],
    caixa: 'padrão',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 5,
    nome: 'Grace',
    skillVermelha: 'DanoFocado',
    skillVerde: 'ijMorto',
    classe: ['Dano'],
    caixa: 'padrão',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 6,
    nome: 'Jack',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'Furto',
    classe: ['Dano', 'Dinheiro'],
    caixa: 'gelo',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 7,
    nome: 'Lady',
    skillVermelha: 'Rebola',
    skillVerde: 'InstAgil',
    classe: ['Errar', 'Dano'],
    caixa: 'fantasma',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 8,
    nome: 'Lanky',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'DanoFocado',
    classe: ['Dano', 'Cura'],
    caixa: 'floresta',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 9,
    nome: 'Lebron',
    skillVermelha: 'AutoCura',
    skillVerde: 'ijFera',
    classe: ['Dano'],
    caixa: 'gelo',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 10,
    nome: 'Lia',
    skillVermelha: 'ijDemo',
    skillVerde: 'CuraGrupo',
    classe: ['Cura', 'Suporte'],
    caixa: 'fogo',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 11,
    nome: 'Lianna',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'AutoCura',
    classe: ['Dano'],
    caixa: 'fantasma',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 12,
    nome: 'Marga',
    skillVermelha: 'AutoCura',
    skillVerde: 'Furto',
    classe: ['Dinheiro', 'Dano'],
    caixa: 'padrão',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 13,
    nome: 'Marla',
    skillVermelha: 'DanoFocado',
    skillVerde: 'Rebola',
    classe: ['Cura', 'Errar'],
    caixa: 'gelo',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 14,
    nome: 'Marvin',
    skillVermelha: 'ijMago',
    skillVerde: 'DanoPerfu',
    classe: ['Errar', 'Dano'],
    caixa: 'padrão',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 15,
    nome: 'Melissa',
    skillVermelha: 'InstAgil',
    skillVerde: 'AutoCura',
    classe: ['Dano'],
    caixa: 'fogo',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 16,
    nome: 'Murka',
    skillVermelha: 'ijFera',
    skillVerde: 'InstAgil',
    classe: ['Dano'],
    caixa: 'padrão',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 17,
    nome: 'Randolfo',
    skillVermelha: 'ijMago',
    skillVerde: 'Rebola',
    classe: ['Errar', 'Suporte', 'Escudo'],
    caixa: 'floresta',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 18,
    nome: 'Sapo',
    skillVermelha: 'Furto',
    skillVerde: 'AutoCura',
    classe: ['Dinheiro', 'Dano'],
    caixa: 'floresta',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 19,
    nome: 'Saul',
    skillVermelha: 'ijHumano',
    skillVerde: 'Furto',
    classe: ['Cura', 'Dinheiro'],
    caixa: 'fantasma',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 20,
    nome: 'Sirmoo',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'ijMorto',
    classe: ['Cura'],
    caixa: 'fantasma',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 21,
    nome: 'Tina',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'InstAgil',
    classe: ['Dano'],
    caixa: 'floresta',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 22,
    nome: 'Wilrond',
    skillVermelha: 'InstAgil',
    skillVerde: 'CuraGrupo',
    classe: ['Dano', 'Cura'],
    caixa: 'padrão',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 23,
    nome: 'Torm',
    skillVermelha: 'DanoFocado',
    skillVerde: 'DanoPerfu',
    classe: ['Dano'],
    caixa: 'fogo',
    dificuldade: 'facil',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 24,
    nome: 'Aang',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'Voodo',
    classe: ['Suporte', 'Cura'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'Elementos',
  ),
  Heroi(
    indice: 25,
    nome: 'Alton',
    skillVermelha: 'Repete',
    skillVerde: 'InstAgil',
    classe: ['Dano', 'Errar'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 26,
    nome: 'Angela',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'InstAgil',
    classe: ['Dano ', 'Cura'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 27,
    nome: 'Betty',
    skillVermelha: 'Rebola',
    skillVerde: 'Furto',
    classe: ['Dano ', 'Furto'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 28,
    nome: 'Contractus',
    skillVermelha: 'NuvemCura',
    skillVerde: 'DanoPerfu',
    classe: ['Dano', 'Suporte'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 29,
    nome: 'Jack',
    skillVermelha: 'Larapio',
    skillVerde: 'Furto',
    classe: ['Dano ', 'Furto'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 30,
    nome: 'Jorge',
    skillVermelha: 'Rebola',
    skillVerde: 'NuvemCura',
    classe: ['Suporte', 'Cura'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 31,
    nome: 'Lã',
    skillVermelha: 'Furto',
    skillVerde: 'InstSobrev',
    classe: ['Dano', 'Furto'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 32,
    nome: 'Morgana',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'InstSobrev',
    classe: ['Cura', 'Suporte'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 33,
    nome: 'Polar',
    skillVermelha: 'DanoFocado',
    skillVerde: 'ijHumano',
    classe: ['Dano'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 34,
    nome: 'Reri',
    skillVermelha: 'Voodo',
    skillVerde: 'ijMorto',
    classe: ['Suporte', 'Dano', 'Errar'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 35,
    nome: 'Ruth',
    skillVermelha: 'Larapio',
    skillVerde: 'AutoCura',
    classe: ['Suporte', 'Dano'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 36,
    nome: 'Show',
    skillVermelha: 'Furto',
    skillVerde: 'AutoCura',
    classe: ['Furto', 'Dano'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 37,
    nome: 'Truta',
    skillVermelha: 'ijHumano',
    skillVerde: 'InstAgil',
    classe: ['Dano'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 38,
    nome: 'Tuco',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'AutoCura',
    classe: ['Dano'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 39,
    nome: 'Uni',
    skillVermelha: 'InstSobrev',
    skillVerde: 'InstAgil',
    classe: ['Dano', 'Errar'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 40,
    nome: 'Willy',
    skillVermelha: 'InstSobrev',
    skillVerde: 'Repete',
    classe: ['Suporte', 'Errar'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'nao',
  ),
  Heroi(
    indice: 41,
    nome: 'Zhang',
    skillVermelha: 'Rebola',
    skillVerde: 'NuvemCura',
    classe: ['Suporte', 'Cura'],
    caixa: 'W box',
    dificuldade: 'medio',
    cartaextra: 'Mapa Estelar',
  ),
];

class HeroiAux extends Heroi {
  const HeroiAux({
    super.skillVermelha = '',
    super.skillVerde = '',
    super.classe = const [],
    super.caixa = '',
    super.dificuldade = '',
    required super.indice,
    required super.nome,
    required super.cartaextra,
  });
}

const List<HeroiAux> heroisAux = [
  HeroiAux(indice: 0, nome: 'Elementos', cartaextra: 'Aang'),
  HeroiAux(indice: 1, nome: 'Elementos', cartaextra: 'Zhang'),
];
