class Heroi {
  final int indice;
  final String nome;
  final String skillVermelha;
  final String skillVerde;
  final List<String> classe;
  final String caixa;
  final String dificuldade;

  const Heroi({
    required this.indice,
    required this.nome,
    required this.skillVermelha,
    required this.skillVerde,
    required this.classe,
    required this.caixa,
    required this.dificuldade,
  });
}

const List<Heroi> herois = [
  Heroi(
    indice: 0,
    nome: 'Aristides',
    skillVermelha: 'InstAgil',
    skillVerde: 'CuraGrupo',
    classe: ['Suporte'],
    caixa: 'torre',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 1,
    nome: 'Brad',
    skillVermelha: 'ijDemo',
    skillVerde: 'Rebola',
    classe: ['Cura'],
    caixa: 'padrão',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 2,
    nome: 'Broque',
    skillVermelha: 'Furto',
    skillVerde: 'ijOrc',
    classe: ['Suporte'],
    caixa: 'fogo',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 3,
    nome: 'Dedouro',
    skillVermelha: 'ijHumano',
    skillVerde: 'Furto',
    classe: ['Dinheiro'],
    caixa: 'padrão',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 4,
    nome: 'Edith',
    skillVermelha: 'Rebola',
    skillVerde: 'ijOrc',
    classe: ['Cura'],
    caixa: 'padrão',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 5,
    nome: 'Grace',
    skillVermelha: 'DanoFocado',
    skillVerde: 'ijMorto',
    classe: ['Dano'],
    caixa: 'padrão',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 6,
    nome: 'Jack',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'Furto',
    classe: ['Dano', 'Dinheiro'],
    caixa: 'padrão',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 7,
    nome: 'Lady',
    skillVermelha: 'Rebola',
    skillVerde: 'InstAgil',
    classe: ['Errar', 'Dano'],
    caixa: 'fantasma',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 8,
    nome: 'Lanky',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'DanoFocado',
    classe: ['Dano', 'Cura'],
    caixa: 'floresta',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 9,
    nome: 'Lebron',
    skillVermelha: 'AutoCura',
    skillVerde: 'ijFera',
    classe: ['Dano'],
    caixa: 'torre',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 10,
    nome: 'Lia',
    skillVermelha: 'ijDemo',
    skillVerde: 'CuraGrupo',
    classe: ['Cura', 'Suporte'],
    caixa: 'fogo',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 11,
    nome: 'Lianna',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'AutoCura',
    classe: ['Dano'],
    caixa: 'fantasma',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 12,
    nome: 'Marga',
    skillVermelha: 'AutoCura',
    skillVerde: 'Furto',
    classe: ['Dinheiro', 'Dano'],
    caixa: 'padrão',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 13,
    nome: 'Marla',
    skillVermelha: 'DanoFocado',
    skillVerde: 'Rebola',
    classe: ['Cura', 'Errar'],
    caixa: 'torre',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 14,
    nome: 'Marvin',
    skillVermelha: 'ijMago',
    skillVerde: 'DanoPerfu',
    classe: ['Errar', 'Dano'],
    caixa: 'padrão',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 15,
    nome: 'Melissa',
    skillVermelha: 'InstAgil',
    skillVerde: 'AutoCura',
    classe: ['Dano'],
    caixa: 'fogo',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 16,
    nome: 'Murka',
    skillVermelha: 'ijFera',
    skillVerde: 'InstAgil',
    classe: ['Dano'],
    caixa: 'padrão',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 17,
    nome: 'Randolfo',
    skillVermelha: 'ijMago',
    skillVerde: 'Rebola',
    classe: ['Errar', 'Suporte', 'Escudo'],
    caixa: 'floresta',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 18,
    nome: 'Sapo',
    skillVermelha: 'Furto',
    skillVerde: 'AutoCura',
    classe: ['Dinheiro', 'Dano'],
    caixa: 'floresta',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 19,
    nome: 'Saul',
    skillVermelha: 'ijHumano',
    skillVerde: 'Furto',
    classe: ['Cura', 'Dinheiro'],
    caixa: 'fantasma',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 20,
    nome: 'Sirmoo',
    skillVermelha: 'CuraGrupo',
    skillVerde: 'ijMorto',
    classe: ['Cura'],
    caixa: 'fantasma',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 21,
    nome: 'Tina',
    skillVermelha: 'DanoPerfu',
    skillVerde: 'InstAgil',
    classe: ['Dano'],
    caixa: 'floresta',
    dificuldade: 'facil',
  ),
  Heroi(
    indice: 22,
    nome: 'Wilrond',
    skillVermelha: 'InstAgil',
    skillVerde: 'CuraGrupo',
    classe: ['Dano', 'Cura'],
    caixa: 'padrão',
    dificuldade: 'facil',
  ),
];
